# Generated by Django 5.2.7 on 2025-11-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1拍', '1拍'), ('2拍', '2拍'), ('3拍', '3拍'), ('4拍', '4拍')], max_length=10, null=True, verbose_name='拍別')),
                ('auctionDate', models.DateField(blank=True, null=True, verbose_name='拍賣日')),
                ('floorPrice', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='底價')),
                ('pingPrice', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='坪價')),
                ('CP', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='CP')),
                ('click', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='點閱')),
                ('monitor', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='監控')),
                ('caseCount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='成交件數')),
                ('margin', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='保証金')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Bouns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounsRate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='加成')),
                ('bounsReason', models.CharField(blank=True, max_length=100, null=True, verbose_name='加成原因')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildNumber', models.CharField(max_length=100, null=True, verbose_name='建號')),
                ('url', models.URLField(blank=True, null=True, verbose_name='謄本')),
                ('area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='建坪(平方公尺)')),
                ('holdingPointPersonal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='個人持分')),
                ('holdingPointAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='所有持分')),
                ('calculatedArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='計算後建坪')),
                ('typeUse', models.CharField(blank=True, max_length=100, null=True, verbose_name='建物型')),
                ('usePartition', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用分區')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='備註')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.CharField(max_length=100, verbose_name='案號(*)')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='所屬公司')),
                ('bigSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='段號')),
                ('smallSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='小段')),
                ('village', models.CharField(blank=True, max_length=100, null=True, verbose_name='村里')),
                ('neighbor', models.CharField(blank=True, max_length=100, null=True, verbose_name='鄰')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='街路')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='段')),
                ('lane', models.CharField(blank=True, max_length=100, null=True, verbose_name='巷')),
                ('alley', models.CharField(blank=True, max_length=100, null=True, verbose_name='弄')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='號')),
                ('Floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='案件狀態')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='案件最後更新時間')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='案件建立時間')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='城市')),
            ],
            options={
                'db_table': 'yfcase_city',
            },
        ),
        migrations.CreateModel(
            name='FinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalDecision', models.CharField(blank=True, max_length=10, null=True, verbose_name='最終判定')),
                ('remark', models.CharField(blank=True, max_length=3000, null=True, verbose_name='備註')),
                ('type', models.CharField(blank=True, max_length=3000, null=True, verbose_name='分類')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='人員')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('workArea', models.CharField(blank=True, max_length=10, null=True, verbose_name='工作轄區')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landNumber', models.CharField(max_length=100, null=True, verbose_name='地號')),
                ('url', models.URLField(blank=True, null=True, verbose_name='謄本')),
                ('area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='地坪(平方公尺)')),
                ('holdingPointPersonal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='個人持分')),
                ('holdingPointAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='所有持分')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='備註')),
                ('calculatedArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='計算後地坪(坪)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('自訂', '自訂'), ('實價登錄', '實價登錄'), ('好時價', '好時價')], default='自訂', max_length=100, null=True, verbose_name='類型')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='附件')),
                ('houseAge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='屋齡(年)')),
                ('transactionDate', models.DateField(blank=True, null=True, verbose_name='成交日期')),
                ('floorHeight', models.CharField(blank=True, max_length=100, null=True, verbose_name='樓高')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='總價')),
                ('buildArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='建坪(坪)')),
                ('subBuildArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='增建坪數(坪)')),
                ('unitPrice', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='單價')),
                ('calculate', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='計算')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='案號')),
                ('type', models.CharField(blank=True, choices=[('法拍', '法拍'), ('分割共有物', '分割共有物'), ('不當得利', '不當得利'), ('遷讓房屋', '遷讓房屋'), ('訴訟費用額(利)', '訴訟費用額(利)'), ('訴訟費用額(割)', '訴訟費用額(割)'), ('訴訟費用額(遷)', '訴訟費用額(遷)'), ('強制執行(變價)', '強制執行(變價)'), ('強制執行(清償)', '強制執行(清償)')], default='法拍', max_length=100, null=True, verbose_name='案別')),
                ('stock', models.CharField(blank=True, choices=[('忠', '忠'), ('孝', '孝')], default='忠', max_length=100, null=True, verbose_name='股別')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話')),
                ('ext', models.CharField(blank=True, max_length=100, null=True, verbose_name='分機')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('type', models.CharField(max_length=30, verbose_name='分類')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='電話')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopBuyDate', models.DateField(blank=True, null=True, verbose_name='應買止日')),
                ('actionResult', models.CharField(blank=True, choices=[('', ''), ('撤回', '撤回'), ('第三人搶標', '第三人搶標'), ('等待優購', '等待優購'), ('遭優購', '遭優購'), ('無人優購', '無人優購')], max_length=20, null=True, verbose_name='執行結果')),
                ('bidAuctionTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='搶標拍別')),
                ('bidMoney', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='搶標金額')),
                ('objectNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='標的編號')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstDay', models.DateField(blank=True, null=True, verbose_name='初勘日')),
                ('secondDay', models.DateField(blank=True, null=True, verbose_name='會勘日')),
                ('foreclosureAnnouncementLink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='法拍公告(證物三)')),
                ('house988Link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='998連結')),
                ('objectPhotoLink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='物件照片(證物四)')),
                ('netMarketPriceLink', models.URLField(blank=True, max_length=1000, null=True)),
                ('foreclosureRecordLink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='法拍記錄(證物七)')),
                ('objectViewLink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='標的物(現場勘查)')),
                ('pagesViewLink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='收發文薄')),
                ('moneytViewLink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='流水帳')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='鄉鎮')),
                ('zip_code', models.CharField(max_length=30, verbose_name='郵遞區號')),
                ('district_court', models.CharField(max_length=30, verbose_name='地方法院')),
                ('land_office', models.CharField(max_length=30, verbose_name='地政事務所')),
                ('finance_and_tax_bureau', models.CharField(max_length=30, verbose_name='財政稅務局')),
                ('police_station', models.CharField(max_length=30, verbose_name='警察局')),
                ('irs', models.CharField(max_length=30, verbose_name='國稅局')),
                ('home_office', models.CharField(max_length=30, verbose_name='戶政事務所')),
            ],
            options={
                'db_table': 'yfcase_township',
            },
        ),
    ]
