# Generated by Django 5.2.7 on 2025-11-04 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bouns',
            name='bounsPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouns_set', to=settings.AUTH_USER_MODEL, verbose_name='勘查員'),
        ),
        migrations.AddField(
            model_name='cases',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='區域負責人'),
        ),
        migrations.AddField(
            model_name='build',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='pages.cases', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='auction',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='pages.cases'),
        ),
        migrations.AddField(
            model_name='cases',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.city', verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finaldecisions', to='pages.cases', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='land',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='pages.cases', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectbuilds', to='pages.cases', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='bouns',
            name='objectbuild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounses', to='pages.objectbuild'),
        ),
        migrations.AddField(
            model_name='officialdocuments',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officialdocuments', to='pages.cases'),
        ),
        migrations.AddField(
            model_name='person',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='pages.cases', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='result',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pages.cases', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='survey',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='pages.cases', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='township',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.city'),
        ),
        migrations.AddField(
            model_name='cases',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.township', verbose_name='鄉鎮區里'),
        ),
    ]
