# Generated by Django 5.2.7 on 2025-12-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['auctionDate', 'id']},
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='人員'),
        ),
        migrations.AlterField(
            model_name='result',
            name='actionResult',
            field=models.CharField(blank=True, choices=[('', ''), ('撤回', '撤回'), ('第三人搶標', '第三人搶標'), ('等待優購', '等待優購'), ('遭優購', '遭優購'), ('無人優購', '無人優購'), ('四拍流標', '四拍流標')], max_length=20, null=True, verbose_name='執行結果'),
        ),
    ]
