# Generated by Django 5.2.7 on 2025-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_increase_finaldecision_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='holdingShareDenominator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='持分比例(分母)'),
        ),
        migrations.AddField(
            model_name='person',
            name='holdingShareNumerator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='持分比例(分子)'),
        ),
        migrations.AddField(
            model_name='person',
            name='investmentDenominator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='投資比例(分母)'),
        ),
        migrations.AddField(
            model_name='person',
            name='investmentNumerator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='投資比例(分子)'),
        ),
        migrations.AddField(
            model_name='person',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='備註'),
        ),
    ]
