# Generated by Django 5.2.7 on 2025-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_person_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='holdingShareDenominator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='持分比例(所有)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='holdingShareNumerator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='持分比例(個人)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='investmentDenominator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='投資比例(所有)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='investmentNumerator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='投資比例(個人)'),
        ),
    ]
