# Generated by Django 5.2.7 on 2025-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_person_holdingsharedenominator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peterpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
            ],
        ),
    ]
